"""
JARVIS Database Module
Handles persistent storage of all trades, signals, and configurations
ENSURES TRADE HISTORY IS NEVER LOST
"""

import sqlite3
from datetime import datetime
from typing import Dict, List, Optional
import json
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class JarvisDatabase:
    """
    Persistent storage for JARVIS trades and signals
    Saves ALL trade history - never wipes data
    """
    
    def __init__(self, db_path: str = "jarvis_trades.db"):
        self.db_path = db_path
        self.conn = None
        self.create_tables()
        logger.info(f"✅ Database initialized: {db_path}")
    
    def get_connection(self):
        """Get database connection"""
        if self.conn is None:
            self.conn = sqlite3.connect(self.db_path, check_same_thread=False)
            self.conn.row_factory = sqlite3.Row
        return self.conn
    
    def create_tables(self):
        """Create all necessary tables for persistent storage"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        # Signals table - stores ALL signals generated by JARVIS
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp DATETIME NOT NULL,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                signal_type TEXT NOT NULL,
                entry_price REAL NOT NULL,
                stop_loss REAL NOT NULL,
                take_profit REAL NOT NULL,
                partial_tp REAL,
                atr REAL,
                rsi REAL,
                market_trend TEXT,
                htf_trend TEXT,
                risk_reward REAL,
                structure_data TEXT,
                zones_data TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        
        # Trades table - tracks opened positions
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                signal_id INTEGER,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                direction TEXT NOT NULL,
                entry_price REAL NOT NULL,
                entry_time DATETIME NOT NULL,
                stop_loss REAL NOT NULL,
                take_profit REAL NOT NULL,
                partial_tp REAL,
                partial_tp_hit BOOLEAN DEFAULT 0,
                position_size REAL,
                status TEXT DEFAULT 'OPEN',
                exit_price REAL,
                exit_time DATETIME,
                pnl REAL,
                pnl_percent REAL,
                exit_reason TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (signal_id) REFERENCES signals (id)
            )
        ''')
        
        # Trade history - complete record of all closed trades
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS trade_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                trade_id INTEGER,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                direction TEXT NOT NULL,
                entry_price REAL NOT NULL,
                entry_time DATETIME NOT NULL,
                exit_price REAL NOT NULL,
                exit_time DATETIME NOT NULL,
                stop_loss REAL NOT NULL,
                take_profit REAL NOT NULL,
                partial_tp_hit BOOLEAN DEFAULT 0,
                pnl REAL NOT NULL,
                pnl_percent REAL NOT NULL,
                risk_reward REAL,
                result TEXT NOT NULL,
                exit_reason TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (trade_id) REFERENCES trades (id)
            )
        ''')
        
        # Performance stats - aggregated performance metrics
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS performance_stats (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                timeframe TEXT NOT NULL,
                total_trades INTEGER DEFAULT 0,
                winning_trades INTEGER DEFAULT 0,
                losing_trades INTEGER DEFAULT 0,
                total_pnl REAL DEFAULT 0,
                total_pnl_percent REAL DEFAULT 0,
                win_rate REAL DEFAULT 0,
                profit_factor REAL DEFAULT 0,
                avg_win REAL DEFAULT 0,
                avg_loss REAL DEFAULT 0,
                largest_win REAL DEFAULT 0,
                largest_loss REAL DEFAULT 0,
                last_updated DATETIME DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        
        # Configuration table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS config (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        
        conn.commit()
        logger.info("📊 Database tables created successfully")
    
    def save_signal(self, signal_data: Dict) -> int:
        """
        Save a new signal to database
        Returns the signal ID
        """
        conn = self.get_connection()
        cursor = conn.cursor()
        
        cursor.execute('''
            INSERT INTO signals (
                timestamp, symbol, timeframe, signal_type,
                entry_price, stop_loss, take_profit, partial_tp,
                atr, rsi, market_trend, htf_trend, risk_reward,
                structure_data, zones_data
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            signal_data.get('timestamp', datetime.now()),
            signal_data.get('symbol'),
            signal_data.get('timeframe'),
            signal_data.get('signal'),
            signal_data.get('entry_price'),
            signal_data.get('stop_loss'),
            signal_data.get('take_profit'),
            signal_data.get('partial_tp'),
            signal_data.get('atr'),
            signal_data.get('rsi'),
            signal_data.get('market_trend'),
            signal_data.get('htf_trend'),
            signal_data.get('risk_reward'),
            json.dumps(signal_data.get('structure', {})),
            json.dumps(signal_data.get('zones', {}))
        ))
        
        conn.commit()
        signal_id = cursor.lastrowid
        
        logger.info(f"💾 Signal saved: {signal_data.get('signal')} at {signal_data.get('entry_price')}")
        return signal_id
    
    def create_trade(self, signal_id: int, signal_data: Dict, position_size: float = 1.0) -> int:
        """
        Create a new trade based on a signal
        Returns trade ID
        """
        conn = self.get_connection()
        cursor = conn.cursor()
        
        cursor.execute('''
            INSERT INTO trades (
                signal_id, symbol, timeframe, direction,
                entry_price, entry_time, stop_loss, take_profit,
                partial_tp, position_size, status
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            signal_id,
            signal_data.get('symbol'),
            signal_data.get('timeframe'),
            signal_data.get('signal'),
            signal_data.get('entry_price'),
            signal_data.get('timestamp', datetime.now()),
            signal_data.get('stop_loss'),
            signal_data.get('take_profit'),
            signal_data.get('partial_tp'),
            position_size,
            'OPEN'
        ))
        
        conn.commit()
        trade_id = cursor.lastrowid
        
        logger.info(f"📈 Trade created: ID {trade_id}, {signal_data.get('signal')} {signal_data.get('symbol')}")
        return trade_id
    
    def update_trade_status(self, trade_id: int, current_price: float) -> Optional[Dict]:
        """
        Update trade status based on current price
        Returns trade update info if status changed
        """
        conn = self.get_connection()
        cursor = conn.cursor()
        
        # Get trade details
        cursor.execute('SELECT * FROM trades WHERE id = ? AND status = "OPEN"', (trade_id,))
        trade = cursor.fetchone()
        
        if not trade:
            return None
        
        trade_dict = dict(trade)
        direction = trade_dict['direction']
        entry_price = trade_dict['entry_price']
        stop_loss = trade_dict['stop_loss']
        take_profit = trade_dict['take_profit']
        partial_tp = trade_dict['partial_tp']
        partial_tp_hit = trade_dict['partial_tp_hit']
        
        update_info = None
        
        # Check for partial TP hit
        if partial_tp and not partial_tp_hit:
            if direction == 'LONG' and current_price >= partial_tp:
                cursor.execute('''
                    UPDATE trades SET partial_tp_hit = 1 WHERE id = ?
                ''', (trade_id,))
                conn.commit()
                update_info = {'type': 'PARTIAL_TP', 'price': current_price}
                logger.info(f"🎯 Partial TP hit for trade {trade_id} at {current_price}")
            
            elif direction == 'SHORT' and current_price <= partial_tp:
                cursor.execute('''
                    UPDATE trades SET partial_tp_hit = 1 WHERE id = ?
                ''', (trade_id,))
                conn.commit()
                update_info = {'type': 'PARTIAL_TP', 'price': current_price}
                logger.info(f"🎯 Partial TP hit for trade {trade_id} at {current_price}")
        
        # Check for full TP or SL hit
        exit_reason = None
        exit_price = None
        
        if direction == 'LONG':
            if current_price >= take_profit:
                exit_reason = 'TAKE_PROFIT'
                exit_price = take_profit
            elif current_price <= stop_loss:
                exit_reason = 'STOP_LOSS'
                exit_price = stop_loss
        
        elif direction == 'SHORT':
            if current_price <= take_profit:
                exit_reason = 'TAKE_PROFIT'
                exit_price = take_profit
            elif current_price >= stop_loss:
                exit_reason = 'STOP_LOSS'
                exit_price = stop_loss
        
        if exit_reason:
            # Calculate P&L
            if direction == 'LONG':
                pnl = exit_price - entry_price
            else:
                pnl = entry_price - exit_price
            
            pnl_percent = (pnl / entry_price) * 100
            
            # Close trade
            cursor.execute('''
                UPDATE trades 
                SET status = 'CLOSED', exit_price = ?, exit_time = ?, 
                    pnl = ?, pnl_percent = ?, exit_reason = ?
                WHERE id = ?
            ''', (exit_price, datetime.now(), pnl, pnl_percent, exit_reason, trade_id))
            
            # Add to trade history
            self._add_to_history(trade_dict, exit_price, pnl, pnl_percent, exit_reason)
            
            # Update performance stats
            self._update_performance_stats(trade_dict, pnl, pnl_percent, exit_reason)
            
            conn.commit()
            
            update_info = {
                'type': 'CLOSED',
                'reason': exit_reason,
                'exit_price': exit_price,
                'pnl': pnl,
                'pnl_percent': pnl_percent
            }
            
            logger.info(f"✅ Trade {trade_id} closed: {exit_reason} | P&L: {pnl_percent:.2f}%")
        
        return update_info
    
    def _add_to_history(self, trade: Dict, exit_price: float, pnl: float, 
                        pnl_percent: float, exit_reason: str):
        """Add closed trade to history"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        result = 'WIN' if pnl > 0 else 'LOSS'
        
        cursor.execute('''
            INSERT INTO trade_history (
                trade_id, symbol, timeframe, direction, entry_price,
                entry_time, exit_price, exit_time, stop_loss, take_profit,
                partial_tp_hit, pnl, pnl_percent, result, exit_reason
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            trade['id'], trade['symbol'], trade['timeframe'], trade['direction'],
            trade['entry_price'], trade['entry_time'], exit_price, datetime.now(),
            trade['stop_loss'], trade['take_profit'], trade['partial_tp_hit'],
            pnl, pnl_percent, result, exit_reason
        ))
        
        conn.commit()
    
    def _update_performance_stats(self, trade: Dict, pnl: float, 
                                  pnl_percent: float, exit_reason: str):
        """Update aggregated performance statistics"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        symbol = trade['symbol']
        timeframe = trade['timeframe']
        
        # Get existing stats or create new
        cursor.execute('''
            SELECT * FROM performance_stats 
            WHERE symbol = ? AND timeframe = ?
        ''', (symbol, timeframe))
        
        stats = cursor.fetchone()
        
        if stats:
            stats_dict = dict(stats)
            total_trades = stats_dict['total_trades'] + 1
            winning_trades = stats_dict['winning_trades'] + (1 if pnl > 0 else 0)
            losing_trades = stats_dict['losing_trades'] + (1 if pnl <= 0 else 0)
            total_pnl = stats_dict['total_pnl'] + pnl
            total_pnl_percent = stats_dict['total_pnl_percent'] + pnl_percent
            win_rate = (winning_trades / total_trades) * 100 if total_trades > 0 else 0
            
            # Update largest win/loss
            largest_win = max(stats_dict['largest_win'], pnl) if pnl > 0 else stats_dict['largest_win']
            largest_loss = min(stats_dict['largest_loss'], pnl) if pnl < 0 else stats_dict['largest_loss']
            
            cursor.execute('''
                UPDATE performance_stats 
                SET total_trades = ?, winning_trades = ?, losing_trades = ?,
                    total_pnl = ?, total_pnl_percent = ?, win_rate = ?,
                    largest_win = ?, largest_loss = ?, last_updated = ?
                WHERE symbol = ? AND timeframe = ?
            ''', (
                total_trades, winning_trades, losing_trades,
                total_pnl, total_pnl_percent, win_rate,
                largest_win, largest_loss, datetime.now(),
                symbol, timeframe
            ))
        else:
            # Create new stats entry
            winning_trades = 1 if pnl > 0 else 0
            losing_trades = 1 if pnl <= 0 else 0
            win_rate = (winning_trades / 1) * 100
            
            cursor.execute('''
                INSERT INTO performance_stats (
                    symbol, timeframe, total_trades, winning_trades, losing_trades,
                    total_pnl, total_pnl_percent, win_rate, largest_win, largest_loss
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                symbol, timeframe, 1, winning_trades, losing_trades,
                pnl, pnl_percent, win_rate,
                pnl if pnl > 0 else 0, pnl if pnl < 0 else 0
            ))
        
        conn.commit()
    
    def get_all_signals(self, limit: int = 100, symbol: str = None) -> List[Dict]:
        """Get all signals from database"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        if symbol:
            cursor.execute('''
                SELECT * FROM signals WHERE symbol = ? 
                ORDER BY timestamp DESC LIMIT ?
            ''', (symbol, limit))
        else:
            cursor.execute('''
                SELECT * FROM signals 
                ORDER BY timestamp DESC LIMIT ?
            ''', (limit,))
        
        signals = cursor.fetchall()
        return [dict(signal) for signal in signals]
    
    def get_open_trades(self, symbol: str = None) -> List[Dict]:
        """Get all open trades"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        if symbol:
            cursor.execute('''
                SELECT * FROM trades 
                WHERE status = "OPEN" AND symbol = ?
                ORDER BY entry_time DESC
            ''', (symbol,))
        else:
            cursor.execute('''
                SELECT * FROM trades 
                WHERE status = "OPEN"
                ORDER BY entry_time DESC
            ''')
        
        trades = cursor.fetchall()
        return [dict(trade) for trade in trades]
    
    def get_trade_history(self, limit: int = 100, symbol: str = None) -> List[Dict]:
        """Get trade history - NEVER DELETED"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        if symbol:
            cursor.execute('''
                SELECT * FROM trade_history 
                WHERE symbol = ?
                ORDER BY exit_time DESC LIMIT ?
            ''', (symbol, limit))
        else:
            cursor.execute('''
                SELECT * FROM trade_history 
                ORDER BY exit_time DESC LIMIT ?
            ''', (limit,))
        
        history = cursor.fetchall()
        return [dict(h) for h in history]
    
    def get_performance_stats(self, symbol: str, timeframe: str) -> Optional[Dict]:
        """Get performance statistics"""
        conn = self.get_connection()
        cursor = conn.cursor()
        
        cursor.execute('''
            SELECT * FROM performance_stats 
            WHERE symbol = ? AND timeframe = ?
        ''', (symbol, timeframe))
        
        stats = cursor.fetchone()
        return dict(stats) if stats else None
    
    def close(self):
        """Close database connection"""
        if self.conn:
            self.conn.close()
            self.conn = None


# Test the database
if __name__ == "__main__":
    db = JarvisDatabase("test_jarvis.db")
    
    # Test signal
    test_signal = {
        'timestamp': datetime.now(),
        'symbol': 'BTCUSDT',
        'timeframe': '4h',
        'signal': 'LONG',
        'entry_price': 69000.0,
        'stop_loss': 68500.0,
        'take_profit': 70500.0,
        'partial_tp': 69750.0,
        'atr': 500.0,
        'rsi': 55.0,
        'market_trend': 'BULLISH',
        'htf_trend': 'BULLISH',
        'risk_reward': 3.0,
        'structure': {},
        'zones': {}
    }
    
    signal_id = db.save_signal(test_signal)
    print(f"✅ Signal saved with ID: {signal_id}")
    
    trade_id = db.create_trade(signal_id, test_signal, 1.0)
    print(f"✅ Trade created with ID: {trade_id}")
    
    # Get all signals
    signals = db.get_all_signals()
    print(f"✅ Total signals in database: {len(signals)}")
    
    db.close()
